[build]
  command = "npm run build"
  publish = "_site"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://brainards-new.netlify.app/*"
  to = "https://brainards-new.netlify.app/:splat"
  status = 200
  force = false
